site_name: RegExpInterpreter
nav:
    - 'index.md'
    - 'Installation.md'
    - 'Language_guide.md'
    - 'Interpreter.md'
    - 'QuadTree.md'
    - 'ATMLibrary'
    - 'Structure.md'
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
